spring.application.name=usermanagement
user.service.service-name = User Service
user.service.version=1.0.0
user.service.max-users-per-page=20
user.service.environment=dev
spring.profiles.active=dev
management.endpoints.web.exposure.include=health,info, metrics
management.endpoint.health.show-details=always
info.app.name=${user.service.service-name}
info.app.version=${user.service.version}

app.instance.id=instance-1
app.instance.region=us-east-1